name: 'Setup'
description: 'Install Node 20 and run npm ci'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          functions/package-lock.json

    - name: Install dependencies
      shell: bash
      run: npm ci --prefer-offline --no-audit
