name: 'Start Firebase Emulators'
description: 'Cache emulator binaries, start Firestore and Storage emulators, wait for readiness, and seed test data'

runs:
  using: composite
  steps:
    - name: Setup Java (required for Firebase emulators)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Firebase emulator binaries
      uses: actions/cache@v4
      with:
        path: ~/.cache/firebase/emulators
        key: firebase-emulators-${{ runner.os }}

    - name: Start Firebase emulators
      shell: bash
      run: |
        setsid npx firebase-tools emulators:start --project=demo-test --only=firestore,storage > emulator.log 2>&1 < /dev/null &
        echo "Emulator started, waiting for readiness..."
        sleep 5
      
    - name: Wait for emulators
      shell: bash
      run: |
        npx wait-on http://localhost:8080 http://localhost:9199 --timeout 60000
        echo "Emulators are ready!"

    - name: Seed emulators with test data
      shell: bash
      run: node scripts/seed-emulators.cjs
