name: 'Start Firebase Emulators'
description: 'Cache emulator binaries, start Firestore and Storage emulators, wait for readiness, and seed test data'

runs:
  using: composite
  steps:
    - name: Cache Firebase emulator binaries
      uses: actions/cache@v4
      with:
        path: ~/.cache/firebase/emulators
        key: firebase-emulators-${{ runner.os }}

    - name: Start Firebase emulators
      shell: bash
      run: |
        nohup npx firebase-tools emulators:start --project=demo-test --only=firestore,storage > emulator.log 2>&1 &
        echo $! > emulator.pid
        sleep 2
      
    - name: Wait for emulators
      shell: bash
      run: npx wait-on http://localhost:8080 http://localhost:9199 --timeout 60000

    - name: Seed emulators with test data
      shell: bash
      run: node scripts/seed-emulators.cjs
